// Mocks generated by Mockito 5.1.0 from annotations
// in clean_mausam/test/features/current_weather/domain/usecases/get_current_weather_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:clean_mausam/core/error/failures.dart' as _i5;
import 'package:clean_mausam/core/location/location_entiry.dart' as _i7;
import 'package:clean_mausam/features/current_weather/domain/entities/current_weather.dart'
    as _i6;
import 'package:clean_mausam/features/current_weather/domain/repositories/current_weather_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [CurrentWeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrentWeatherRepository extends _i1.Mock
    implements _i3.CurrentWeatherRepository {
  MockCurrentWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i6.CurrentWeatherEntity>> getCurrentWeather(
          _i7.LocationEntity? locationEntity) =>
      (super.noSuchMethod(
          Invocation.method(#getCurrentWeather, [locationEntity]),
          returnValue:
              Future<_i2.Either<_i5.Failure, _i6.CurrentWeatherEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.CurrentWeatherEntity>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.CurrentWeatherEntity>>);
}
